table Date_Table
	lineageTag: d69d77ae-4be2-4830-a048-4ac4fb1b7b84

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62f0488a-aa19-4fd0-9469-e3b0d0b6b6b1
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4dd51914-6ace-4cc7-bfa2-ab23bc5fcba5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column QuarterOfYear
		dataType: int64
		formatString: 0
		lineageTag: 2b5b609c-cdc1-435b-bd6c-609a2537a088
		summarizeBy: sum
		sourceColumn: QuarterOfYear

		annotation SummarizationSetBy = Automatic

	column MonthOfYear
		dataType: int64
		formatString: 0
		lineageTag: c49ca477-718c-4f7d-864d-4fdf7e706d9f
		summarizeBy: sum
		sourceColumn: MonthOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 980a1a79-da9b-4e7d-95f2-743cf319f88f
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column DateInt
		dataType: int64
		formatString: 0
		lineageTag: b9cb8069-bfb2-41c8-ac9c-0c95fe3cc552
		summarizeBy: sum
		sourceColumn: DateInt

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: ae334312-d7c9-4ea5-95d7-2073672fa6fb
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Month & Year'
		dataType: string
		lineageTag: 562e8dbf-976d-4f9a-a42c-d3df82684af1
		summarizeBy: none
		sourceColumn: Month & Year

		annotation SummarizationSetBy = Automatic

	column 'Quarter & Year'
		dataType: string
		lineageTag: 87a0311e-7f2e-4aa3-a95b-b456854e5530
		summarizeBy: none
		sourceColumn: Quarter & Year

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: fccb9706-4c53-4018-be14-c18844d849e6
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayOfWeekName
		dataType: string
		lineageTag: 7b42624f-b527-4ef5-a4a0-43505952c8ed
		summarizeBy: none
		sourceColumn: DayOfWeekName

		annotation SummarizationSetBy = Automatic

	column WeekEnding
		dataType: dateTime
		formatString: Long Date
		lineageTag: e82ab129-d7bb-465b-8710-273df853bcdd
		summarizeBy: none
		sourceColumn: WeekEnding

		variation Variation
			isDefault
			relationship: c84b978d-3985-437f-9f04-54ef1abef0cf
			defaultHierarchy: LocalDateTable_950c91dc-e746-4d67-ab2b-1586599aa4aa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEnding
		dataType: dateTime
		formatString: Long Date
		lineageTag: aead930b-75e6-45e8-8500-ae839989e5b0
		summarizeBy: none
		sourceColumn: MonthEnding

		variation Variation
			isDefault
			relationship: b88960e1-4820-4112-9429-70d4457948d8
			defaultHierarchy: LocalDateTable_bf0b0c97-c341-41c1-8d82-bcfca60c12aa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ISO Weeknumber'
		dataType: int64
		formatString: 0
		lineageTag: c3c156a2-a776-4b54-bf1c-b0b626ffba31
		summarizeBy: sum
		sourceColumn: ISO Weeknumber

		annotation SummarizationSetBy = Automatic

	column 'ISO Year'
		dataType: int64
		formatString: 0
		lineageTag: 19b4d9a7-21d2-494d-a2c4-e9c3a8a78e6d
		summarizeBy: sum
		sourceColumn: ISO Year

		annotation SummarizationSetBy = Automatic

	column 'ISO Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 27d1c3d3-0b33-4857-a144-8ce2521ea058
		summarizeBy: sum
		sourceColumn: ISO Day of Year

		annotation SummarizationSetBy = Automatic

	column 'Week & Year'
		dataType: string
		lineageTag: 21578bcf-feff-4b56-88f7-d872793b05e2
		summarizeBy: none
		sourceColumn: Week & Year

		annotation SummarizationSetBy = Automatic

	column WeeknYear
		dataType: int64
		formatString: 0
		lineageTag: 6fac5545-a056-49c4-9b05-808c7bd7a3ab
		summarizeBy: sum
		sourceColumn: WeeknYear

		annotation SummarizationSetBy = Automatic

	column MonthnYear
		dataType: int64
		formatString: 0
		lineageTag: ad098a13-a3db-4e6e-8bdb-55e5076b78ac
		summarizeBy: sum
		sourceColumn: MonthnYear

		annotation SummarizationSetBy = Automatic

	column QuarternYear
		dataType: int64
		formatString: 0
		lineageTag: 12f5a8f4-19eb-4f42-8099-402e5e94bb0a
		summarizeBy: sum
		sourceColumn: QuarternYear

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 4d0696aa-c91e-4346-8de4-fc98b34d93fb
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 329dac29-b89b-46c6-9c96-bfa0a07c16cf
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period'
		dataType: int64
		formatString: 0
		lineageTag: a2e8df76-2f55-4995-bac8-53c4b7a743ad
		summarizeBy: sum
		sourceColumn: Fiscal Period

		annotation SummarizationSetBy = Automatic

	column IsAfterToday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f762ee45-96cb-43ba-9a3a-fde0c2c9f2bd
		summarizeBy: none
		sourceColumn: IsAfterToday

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8aee1d16-6c1a-48ec-8248-62d8e5f36c48
		summarizeBy: none
		sourceColumn: IsWorkingDay

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: d74e7b9c-c20c-4d30-a090-87941b7176c9
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3f7b1cd4-7ed6-4160-9c7c-fc7851f4689b
		summarizeBy: none
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column 'Day Type'
		dataType: string
		lineageTag: 2eea7d1b-3197-4790-93b5-894150e3b81b
		summarizeBy: none
		sourceColumn: Day Type

		annotation SummarizationSetBy = Automatic

	column WeekOffset
		dataType: int64
		formatString: 0
		lineageTag: 487f587e-a3aa-4a9d-b1a9-20051f8233ca
		summarizeBy: sum
		sourceColumn: WeekOffset

		annotation SummarizationSetBy = Automatic

	column MonthOffset
		dataType: int64
		formatString: 0
		lineageTag: df04e70e-4d47-4458-b039-c978f3a88101
		summarizeBy: sum
		sourceColumn: MonthOffset

		annotation SummarizationSetBy = Automatic

	column QuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 43700a7a-3bca-4f63-9f3d-37c129d8ebc9
		summarizeBy: sum
		sourceColumn: QuarterOffset

		annotation SummarizationSetBy = Automatic

	column YearOffset
		dataType: int64
		formatString: 0
		lineageTag: 3afe0868-cff7-46be-9535-6cb2fc3c59e9
		summarizeBy: sum
		sourceColumn: YearOffset

		annotation SummarizationSetBy = Automatic

	column FiscalYearOffset
		dataType: int64
		formatString: 0
		lineageTag: 64bbcc3f-f857-4117-a612-0980af512080
		summarizeBy: sum
		sourceColumn: FiscalYearOffset

		annotation SummarizationSetBy = Automatic

	column WeekCompleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2dbfa311-8334-459f-b956-979377a49f91
		summarizeBy: none
		sourceColumn: WeekCompleted

		annotation SummarizationSetBy = Automatic

	column MonthCompleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4abc7cce-5b1a-4c31-a75b-2195d3aff5a3
		summarizeBy: none
		sourceColumn: MonthCompleted

		annotation SummarizationSetBy = Automatic

	column QuarterCompleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 53149f42-e1bf-4c47-8a35-1c62585a9e60
		summarizeBy: none
		sourceColumn: QuarterCompleted

		annotation SummarizationSetBy = Automatic

	partition Date_Table = m
		mode: import
		source =
				let
				    Source = Query1(#date(2024, 1, 1), #date(2050, 12, 31), null, null, null),
				    #"Extracted Date" = Table.TransformColumns(Source,{}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Date",{{"Date", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

